"""add new models

Revision ID: a66f887222cc
Revises: 7cbb7a4c2e7a
Create Date: 2026-04-26 14:31:45.618953

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "a66f887222cc"
down_revision: Union[str, Sequence[str], None] = "7cbb7a4c2e7a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "skills",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skills")),
        sa.UniqueConstraint("name", name=op.f("uq_skills_name")),
    )
    op.create_table(
        "team_roles",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_team_roles")),
        sa.UniqueConstraint("name", name=op.f("uq_team_roles_name")),
    )
    op.create_table(
        "organizations",
        sa.Column("owner_user_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("contact_email", sa.String(length=255), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_organizations_owner_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
    )
    op.create_table(
        "portfolio_items",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("team_role_id", sa.UUID(), nullable=False),
        sa.Column("project_link", sa.String(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["team_role_id"],
            ["team_roles.id"],
            name=op.f("fk_portfolio_items_team_role_id_team_roles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_portfolio_items_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolio_items")),
    )
    op.create_table(
        "user_skills",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("skill_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
            name=op.f("fk_user_skills_skill_id_skills"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_skills_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "skill_id", name=op.f("pk_user_skills")
        ),
    )
    op.create_table(
        "events",
        sa.Column("organizer_id", sa.UUID(), nullable=True),
        sa.Column("city_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("date_start", sa.DateTime(), nullable=False),
        sa.Column("date_end", sa.DateTime(), nullable=False),
        sa.Column("application_deadline", sa.DateTime(), nullable=True),
        sa.Column(
            "format",
            sa.Enum("online", "offline", name="event_format"),
            nullable=True,
        ),
        sa.Column("registration_link", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "published",
                "registration_open",
                "registration_closed",
                "ongoing",
                "completed",
                "cancelled",
                name="event_status",
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["cities.id"],
            name=op.f("fk_events_city_id_cities"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organizer_id"],
            ["organizations.id"],
            name=op.f("fk_events_organizer_id_organizations"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
    )
    op.create_table(
        "projects",
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("event_id", sa.UUID(), nullable=True),
        sa.Column("city_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "hackathon",
                "startup",
                "study",
                "commercial",
                name="project_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "format",
            sa.Enum("online", "offline", "hybrid", name="project_format"),
            nullable=False,
        ),
        sa.Column("deadline", sa.DateTime(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "SELECTION_COMPLETED",
                "STARTED",
                "ENDED",
                "CANCELED",
                name="project_status",
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["cities.id"],
            name=op.f("fk_projects_city_id_cities"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_projects_event_id_events"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_projects_owner_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )
    op.create_table(
        "project_vacancies",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("team_role_id", sa.UUID(), nullable=False),
        sa.Column("required_count", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "required_count > 0",
            name=op.f(
                "ck_project_vacancies_ck_project_vacancies_required_count_positive"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_project_vacancies_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["team_role_id"],
            ["team_roles.id"],
            name=op.f("fk_project_vacancies_team_role_id_team_roles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_vacancies")),
    )
    op.create_table(
        "team_members",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("team_role_id", sa.UUID(), nullable=True),
        sa.Column("joined_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_team_members_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["team_role_id"],
            ["team_roles.id"],
            name=op.f("fk_team_members_team_role_id_team_roles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_team_members_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_team_members")),
        sa.UniqueConstraint(
            "project_id", "user_id", name="uq_team_members_project_id_user_id"
        ),
    )
    op.create_table(
        "applications",
        sa.Column("vacancy_id", sa.UUID(), nullable=False),
        sa.Column("applicant_id", sa.UUID(), nullable=False),
        sa.Column("cover_letter", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "accepted",
                "rejected",
                "withdrawn",
                name="application_status",
            ),
            nullable=False,
        ),
        sa.Column("decided_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["applicant_id"],
            ["users.id"],
            name=op.f("fk_applications_applicant_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["vacancy_id"],
            ["project_vacancies.id"],
            name=op.f("fk_applications_vacancy_id_project_vacancies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_applications")),
        sa.UniqueConstraint(
            "vacancy_id",
            "applicant_id",
            name="uq_applications_vacancy_id_applicant_id",
        ),
    )
    op.create_table(
        "project_vacancy_skills",
        sa.Column("vacancy_id", sa.UUID(), nullable=False),
        sa.Column("skill_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
            name=op.f("fk_project_vacancy_skills_skill_id_skills"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["vacancy_id"],
            ["project_vacancies.id"],
            name=op.f(
                "fk_project_vacancy_skills_vacancy_id_project_vacancies"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "vacancy_id", "skill_id", name=op.f("pk_project_vacancy_skills")
        ),
    )
    op.alter_column(
        "universities", "city_id", existing_type=sa.UUID(), nullable=False
    )
    op.drop_constraint(
        op.f("fk_universities_city_id_cities"),
        "universities",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_universities_city_id_cities"),
        "universities",
        "cities",
        ["city_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.alter_column(
        "user_profiles", "city_id", existing_type=sa.UUID(), nullable=False
    )
    op.alter_column(
        "user_profiles",
        "university_id",
        existing_type=sa.UUID(),
        nullable=False,
    )
    op.drop_constraint(
        op.f("fk_user_profiles_university_id_universities"),
        "user_profiles",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_user_profiles_city_id_cities"),
        "user_profiles",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_user_profiles_university_id_universities"),
        "user_profiles",
        "universities",
        ["university_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_user_profiles_city_id_cities"),
        "user_profiles",
        "cities",
        ["city_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_user_profiles_city_id_cities"),
        "user_profiles",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_user_profiles_university_id_universities"),
        "user_profiles",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_user_profiles_city_id_cities"),
        "user_profiles",
        "cities",
        ["city_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_user_profiles_university_id_universities"),
        "user_profiles",
        "universities",
        ["university_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.alter_column(
        "user_profiles",
        "university_id",
        existing_type=sa.UUID(),
        nullable=True,
    )
    op.alter_column(
        "user_profiles", "city_id", existing_type=sa.UUID(), nullable=True
    )
    op.drop_constraint(
        op.f("fk_universities_city_id_cities"),
        "universities",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_universities_city_id_cities"),
        "universities",
        "cities",
        ["city_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.alter_column(
        "universities", "city_id", existing_type=sa.UUID(), nullable=True
    )
    op.drop_table("project_vacancy_skills")
    op.drop_table("applications")
    op.drop_table("team_members")
    op.drop_table("project_vacancies")
    op.drop_table("projects")
    op.drop_table("events")
    op.drop_table("user_skills")
    op.drop_table("portfolio_items")
    op.drop_table("organizations")
    op.drop_table("team_roles")
    op.drop_table("skills")
    # ### end Alembic commands ###
