def scope(subject: str, action: str) -> str:
    return f"{subject}:{action}"


class Scope:
    APPLICATIONS_LIST = scope("applications", "list")
    APPLICATIONS_CREATE = scope("applications", "create")
    APPLICATIONS_UPDATE = scope("applications", "update")
    APPLICATIONS_WITHDRAW = scope("applications", "withdraw")
    AUTH_ME = scope("auth", "me")
    AUTH_LOGOUT = scope("auth", "logout")
    AUTH_CHANGE_PASSWORD = scope("auth", "change_password")
    AUTH_QUIT_ALL = scope("auth", "quit_all")
    AUTH_RESEND_VERIFICATION = scope("auth", "resend_verification")
    CITIES_LIST = scope("cities", "list")
    CITIES_DETAIL = scope("cities", "detail")
    CITIES_CREATE = scope("cities", "create")
    CITIES_UPDATE = scope("cities", "update")
    CITIES_DELETE = scope("cities", "delete")
    SKILLS_LIST = scope("skills", "list")
    SKILLS_DETAIL = scope("skills", "detail")
    SKILLS_CREATE = scope("skills", "create")
    SKILLS_UPDATE = scope("skills", "update")
    SKILLS_DELETE = scope("skills", "delete")
    TEAM_ROLES_LIST = scope("team_roles", "list")
    TEAM_ROLES_DETAIL = scope("team_roles", "detail")
    TEAM_ROLES_CREATE = scope("team_roles", "create")
    TEAM_ROLES_UPDATE = scope("team_roles", "update")
    TEAM_ROLES_DELETE = scope("team_roles", "delete")
    UNIVERSITIES_LIST = scope("universities", "list")
    UNIVERSITIES_DETAIL = scope("universities", "detail")
    UNIVERSITIES_CREATE = scope("universities", "create")
    UNIVERSITIES_UPDATE = scope("universities", "update")
    UNIVERSITIES_DELETE = scope("universities", "delete")
    USER_PROFILES_DETAIL = scope("user_profiles", "detail")
    USER_PROFILES_DETAIL_ANY = scope("user_profiles", "detail_any")
    USER_PROFILES_CREATE = scope("user_profiles", "create")
    USER_PROFILES_UPDATE = scope("user_profiles", "update")
    USERS_UPDATE_ROLES = scope("users", "update_roles")
    MONITORING_HEALTH = scope("monitoring", "health")
    PROJECTS_LIST = scope("projects", "list")
    PROJECTS_DETAIL = scope("projects", "detail")
    PROJECTS_CREATE = scope("projects", "create")
    PROJECTS_UPDATE = scope("projects", "update")
    PROJECTS_DELETE = scope("projects", "delete")
    PROJECT_VACANCIES_LIST = scope("project_vacancies", "list")
    PROJECT_VACANCIES_DETAIL = scope("project_vacancies", "detail")
    PROJECT_VACANCIES_CREATE = scope("project_vacancies", "create")
    PROJECT_VACANCIES_UPDATE = scope("project_vacancies", "update")
    PROJECT_VACANCIES_DELETE = scope("project_vacancies", "delete")
